services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: chatbot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data/
    networks:
      - chat

  redis:
    image: redis:7-alpine
    ports:
      - "6389:6379"
    networks:
      - chat
    volumes:
      - redis_data:/data

networks:
  chat:
    name: chat
    driver: bridge

volumes:
  postgres_data:
  redis_data:
